// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gccrvfsshfujbguwlrxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjY3J2ZnNzaGZ1amJndXdscnhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NzExMDYsImV4cCI6MjA2OTE0NzEwNn0.s8fDpKFyDrfeJuxv78UZ1Z4q4LGt9dd9Q1bH9xvdzhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});